=== tinmn9088/dp-lab/lab03-1/src/main/resources/persons.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT persons (person*)>

<!ELEMENT person (first-name,middle-name,last-name,birthday,email)>

<!ELEMENT first-name (#PCDATA)>

<!ELEMENT middle-name (#PCDATA)>

<!ELEMENT last-name (#PCDATA)>

<!ELEMENT birthday (#PCDATA)>

<!ELEMENT email (#PCDATA)>

=== tinmn9088/dp-lab/lab03-1/src/main/resources/persons.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE persons SYSTEM "persons.dtd" >
<persons>
    <person>
        <first-name>Иванов</first-name>
        <middle-name>Иван</middle-name>
        <last-name>Иванович</last-name>
        <birthday>1982-01-01</birthday>
        <email>example@mail.ru</email>
    </person>
    <person>
        <first-name>Петров</first-name>
        <middle-name>Пётр</middle-name>
        <last-name>Петрович</last-name>
        <birthday>1965-02-25</birthday>
        <email>petr1@mail.ru</email>
    </person>
    <person>
        <first-name>Сидоров</first-name>
        <middle-name>Сидор</middle-name>
        <last-name>Сидорович</last-name>
        <birthday>1978-05-03</birthday>
        <email>sidorpomidor@yandex.ru</email>
    </person>
    <person>
        <first-name>Васильев</first-name>
        <middle-name>Василий</middle-name>
        <last-name>Васильевич</last-name>
        <birthday>1991-02-13</birthday>
        <email>brrrr@gmail.com</email>
    </person>
    <person>
        <first-name>Кюльбрехт</first-name>
        <middle-name>Сигизмунд</middle-name>
        <last-name>Эдуардович</last-name>
        <birthday>2000-01-31</birthday>
        <email>tsarz@yahoo.com</email>
    </person>
</persons>
